### ISSUE TITLE
一直提示请先登录

### ISSUE THREAD

**Issue by cainaorun** [stark666/smzdm_bot#1]
一直提示。{'error_code': 99, 'error_msg': '请先登录', 'data': []} 这个，cookie怎么填都不对，大佬能否指导一下

**Comment by xiaokaig** [comment]
同

**Comment by zzw19921212** [comment]
我也是

**Comment by antsman9** [comment]
俺也一样！
![image](https://user-images.githubusercontent.com/38621428/99023894-83bb0900-25a0-11eb-866f-be7eaed19018.png)

**Comment by antsman9** [comment]
> 一直提示。{'error_code': 99, 'error_msg': '请先登录', 'data': []} 这个，cookie怎么填都不对，大佬能否指导一下

估计全部复制不对，也该节选部分内容的吧？

**Comment by zzw19921212** [comment]
> > 一直提示。{'error_code': 99, 'error_msg': '请先登录', 'data': []} 这个，cookie怎么填都不对，大佬能否指导一下
> 
> 估计全部复制不对，应该是节选部分内容的吧？

节选哪些？兄台可否指点一二？

**Comment by antsman9** [comment]
> > > 一直提示。{'error_code': 99, 'error_msg': '请先登录', 'data': []} 这个，cookie怎么填都不对，大佬能否指导一下
> > 
> > 
> > 估计全部复制不对，应该是节选部分内容的吧？
> 
> 节选哪些？兄台可否指点一二？
我去别的地方看 应该是sess=后面

**Comment by cainaorun** [comment]
> > > > 一直提示。{'error_code': 99, 'error_msg': '请先登录', 'data': []} 这个，cookie怎么填都不对，大佬能否指导一下
> > > 
> > > 
> > > 估计全部复制不对，应该是节选部分内容的吧？
> > 
> > 
> > 节选哪些？兄台可否指点一二？
> > 我去别的地方看 应该是sess=后面

还是不行啊……

**Comment by cainaorun** [comment]
本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功

**Comment by zzw19921212** [comment]
> 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功

那就只能等代码更新了？

**Comment by zzw19921212** [comment]
> 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功

意思是还是不行？

**Comment by roc0838** [comment]
> 一直提示。{'error_code': 99, 'error_msg': '请先登录', 'data': []} 这个，cookie怎么填都不对，大佬能否指导一下

在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。

**Comment by roc0838** [comment]
> 我也是

在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。

**Comment by roc0838** [comment]
> 俺也一样！
> ![image](https://user-images.githubusercontent.com/38621428/99023894-83bb0900-25a0-11eb-866f-be7eaed19018.png)

在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。

**Comment by roc0838** [comment]
> > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> 
> 意思是还是不行？

在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。

**Comment by zzw19921212** [comment]
> > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > 
> > 
> > 意思是还是不行？
> 
> 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。

不行，如果改成SMZDM_COOKIE，working失败

**Comment by mima454188** [comment]
> > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > 
> > > 
> > > 意思是还是不行？
> > 
> > 
> > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> 
> 不行，如果改成SMZDM_COOKIE，working失败

不行 失败了

**Comment by mima454188** [comment]
> > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > 
> > > > 
> > > > 意思是还是不行？
> > > 
> > > 
> > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > 
> > 
> > 不行，如果改成SMZDM_COOKIE，working失败
> 
> 不行 失败了

{'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
现在显示这个，不知道是否成功了？

**Comment by antsman9** [comment]
> > > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > > 
> > > > > 
> > > > > 意思是还是不行？
> > > > 
> > > > 
> > > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > > 
> > > 
> > > 不行，如果改成SMZDM_COOKIE，working失败
> > 
> > 
> > 不行 失败了
> 
> {'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
> 现在显示这个，不知道是否成功了？

成功了！

**Comment by zzw19921212** [comment]
> > > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > > 
> > > > > 
> > > > > 意思是还是不行？
> > > > 
> > > > 
> > > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > > 
> > > 
> > > 不行，如果改成SMZDM_COOKIE，working失败
> > 
> > 
> > 不行 失败了
> 
> {'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
> 现在显示这个，不知道是否成功了？

怎么成功的？为啥我改了还是失败

**Comment by zzw19921212** [comment]
> > > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > > 
> > > > > 
> > > > > 意思是还是不行？
> > > > 
> > > > 
> > > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > > 
> > > 
> > > 不行，如果改成SMZDM_COOKIE，working失败
> > 
> > 
> > 不行 失败了
> 
> {'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
> 现在显示这个，不知道是否成功了？

我重新试了一下，又可以了

**Comment by mima454188** [comment]
> > > > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > > > 
> > > > > > 
> > > > > > 意思是还是不行？
> > > > > 
> > > > > 
> > > > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > > > 
> > > > 
> > > > 不行，如果改成SMZDM_COOKIE，working失败
> > > 
> > > 
> > > 不行 失败了
> > 
> > 
> > {'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
> > 现在显示这个，不知道是否成功了？
> 
> 成功了！

可是为什么今早也显示这个，但是我登录什么值得买 签到那块没有显示已签到

**Comment by antsman9** [comment]
你可以试试 2-3天不手动签到，然后在手动，看连签时间是否连续。

**Comment by roc0838** [comment]
> > > > > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > > > > 
> > > > > > > 
> > > > > > > 意思是还是不行？
> > > > > > 
> > > > > > 
> > > > > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > > > > 
> > > > > 
> > > > > 不行，如果改成SMZDM_COOKIE，working失败
> > > > 
> > > > 
> > > > 不行 失败了
> > > 
> > > 
> > > {'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
> > > 现在显示这个，不知道是否成功了？
> > 
> > 
> > 成功了！
> 
> 可是为什么今早也显示这个，但是我登录什么值得买 签到那块没有显示已签到
我也是这样，哈哈，估计是被封了IP?我也不清楚，可以试试qiandao.today里面的服务。

**Comment by mima454188** [comment]
> > > > > > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 意思是还是不行？
> > > > > > > 
> > > > > > > 
> > > > > > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > > > > > 
> > > > > > 
> > > > > > 不行，如果改成SMZDM_COOKIE，working失败
> > > > > 
> > > > > 
> > > > > 不行 失败了
> > > > 
> > > > 
> > > > {'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
> > > > 现在显示这个，不知道是否成功了？
> > > 
> > > 
> > > 成功了！
> > 
> > 
> > 可是为什么今早也显示这个，但是我登录什么值得买 签到那块没有显示已签到
> > 我也是这样，哈哈，估计是被封了IP?我也不清楚，可以试试qiandao.today里面的服务。

最后你成功了吗？

**Comment by roc0838** [comment]
> > > > > > > > > > 本地测试了一下，只需要 sess=xxxx 就可以了，应该是张大妈封杀了github 的IP，没法调试成功
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 意思是还是不行？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 在Settings里面的Secrets参数设置的不对，应该是SMZDM_COOKIE，具体展示实在main.yam文件里面。
> > > > > > > 
> > > > > > > 
> > > > > > > 不行，如果改成SMZDM_COOKIE，working失败
> > > > > > 
> > > > > > 
> > > > > > 不行 失败了
> > > > > 
> > > > > 
> > > > > {'error_code': 0, 'error_msg': '', 'data': {'add_point': 0, 'checkin_num': '2', 'point': 63, 'exp': 1852, 'gold': 2, 'prestige': 0, 'rank': 7, 'slogan': '今日已领0积分，再签到1天可领0积分', 'cards': '2', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False}}
> > > > > 现在显示这个，不知道是否成功了？
> > > > 
> > > > 
> > > > 成功了！
> > > 
> > > 
> > > 可是为什么今早也显示这个，但是我登录什么值得买 签到那块没有显示已签到
> > > 我也是这样，哈哈，估计是被封了IP?我也不清楚，可以试试qiandao.today里面的服务。
> 
> 最后你成功了吗？

我也是和你显示的一样，应该是没有成功。

**Comment by kanjianjiuhao** [comment]
看checkin_num这个数值是不是增加了，这是你连续签到的天数

**Comment by mima454188** [comment]
> 看checkin_num这个数值是不是增加了，这是你连续签到的天数

确实在增加
